---
title: "GrowthCurves"
author: "Maggi Brisbin"
date: "9/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

*GOAL:* 

Create growth curve plots and calculate specific growth rates for each strain, treatment, and transfer with as little repition of code as possible.  

Packages:
```{r}
#install.packages("googlesheets4")
library(googlesheets4) #scrapes google sheets
library(dplyr) # dataframe manipulation
library(ggplot2) # plotting package
```

Import data:
```{r}
fluor<-as.data.frame(read_sheet("https://docs.google.com/spreadsheets/d/11PLCdxknsALJEyMt2ce9BhjkzM_GtxLmCAsQGuYeKeg/edit?usp=sharing"))
fluor$Strain <- as.character(fluor$Strain)
fluor$transfer <- as.character(fluor$transfer)
```

```{r}
fluor %>% dplyr::filter(transfer =="2" & Rep == "1" & Strain != "1528s" & AB == "AB_treated" ) %>% mutate(logRFU = log(Fluoresence)) %>% ggplot(aes(x=Day, y=logRFU))+ geom_point() + facet_wrap(Strain~., scales = "free_y") + theme_bw() + theme(panel.grid.minor = element_blank(), panel.grid.major = element_blank())
```

```{r}
flourforlm1528 <- fluor %>% dplyr::filter(transfer == "2" & Rep == "1" & Strain == "1528c" &Day != 0 ) %>% mutate(logRFU = log(Fluoresence))

lm(Day ~ logRFU, data = flourforlm1528)
```

```{r}
flourforlm629 <- fluor %>% dplyr::filter(transfer == "2" & Rep == "1" & Strain == "629" &Day != 0 ) %>% mutate(logRFU = log(Fluoresence))

lm(Day ~ logRFU, data = flourforlm629)
```


```{r}
flourforlm2710 <- fluor %>% dplyr::filter(transfer == "2" & Rep == "1" & Strain == "2710" & Day != 0 ) %>% mutate(logRFU = log(Fluoresence))

lm(Day ~ logRFU, data = flourforlm2710)
```

```{r}
flourforlmkuro <- fluor %>% dplyr::filter(transfer == "2" & Rep == "1" & Strain == "kuro" & Day != 0 ) %>% mutate(logRFU = log(Fluoresence))

lm(Day ~ logRFU, data = flourforlmkuro)$coefficients[2]
```


```{r}

fluor1<- fluor %>% filter(Strain != "1528s")
  
strains <- unique(fluor1$Strain)

slope <- vector("double", length(strains)) 

for(i in seq_along(strains)) {
  st<-(strains[[i]])
  flourforlm <- fluor %>% dplyr::filter(transfer == "2" & Rep == "1" & Strain == st & Day != 0 ) %>% mutate(logRFU = log(Fluoresence))
  slope[[i]]  <- (lm(Day ~ logRFU, data = flourforlm)$coefficients[2])
  
}

data.frame(strain = strains, m = slope)

```


